# PANDAS

## DATAFRAME<hr>   
* ADD NEW COLUMN
    * TWO OR  MORE COLUMN
    * ONE COLUMN
* DELETE COLUMN
* CHANGE DATATYPE OF COLUMN
* MAP
* APPLY
     * ON ONE COLUMN
     * ON MULTIPLE COLUMN 
* CONCAT
     * AXIS
          * AXIS = 0 (DEFAULT) (top to bottom)
          * AXIS = 1 (left to right)
        
* describe dataframe
    * df.info()  # describe the columns rows , data types , total fill cells
    * df.describe() # mean , std , min | apply only on the numerical columns
    *  df.head() # first 5 rows
    * df.tail() # last 5 rows

In [2]:
import numpy as np
import pandas as pd
total = 1000
s1 = np.random.randint(80 , 100 , total)
ss1 : pd.Series = pd.Series(s1)

s2 = np.random.randint(60 , 80 , total)
ss2 : pd.Series = pd.Series(s2)

print(s2)

[63 75 60 77 60 63 73 76 74 72 74 63 72 71 75 70 62 64 62 62 61 75 77 73
 71 74 64 62 73 78 69 63 75 79 64 78 69 61 70 64 63 60 76 70 70 63 68 64
 60 69 68 68 73 77 65 61 60 72 63 65 65 77 71 72 71 73 63 73 76 77 67 69
 74 65 62 76 66 76 76 73 72 68 69 69 66 69 64 72 75 76 67 63 71 75 72 60
 77 61 73 77 71 70 68 65 75 61 79 66 71 79 79 78 71 73 73 70 64 68 74 65
 67 75 77 79 62 74 62 75 64 78 71 69 63 67 76 79 73 62 66 74 70 74 78 65
 68 63 64 63 60 75 66 69 78 62 62 74 77 70 73 62 64 70 62 69 77 77 62 73
 60 67 64 69 78 70 79 60 70 66 77 72 76 68 69 68 72 64 68 67 70 74 60 73
 72 66 76 75 70 69 73 70 63 66 72 72 64 61 77 61 61 70 66 75 67 74 62 78
 71 73 71 62 67 79 77 77 76 69 62 60 77 63 60 68 77 71 70 74 79 61 62 60
 60 76 63 62 63 77 78 63 71 60 62 74 61 64 64 66 67 71 64 70 73 60 76 75
 76 61 73 64 73 72 78 72 67 77 65 72 60 66 60 70 60 78 67 69 71 66 78 72
 64 67 77 70 69 73 76 66 64 74 62 60 73 73 77 69 61 77 77 72 79 77 79 79
 67 69 64 77 60 70 76 78 71 65 75 70 76 66 60 66 71 79 67 65 70 61 74 65
 66 74 69 70 65 60 68 65 68 67 67 62 66 78 79 69 69 66 69 62 78 72 67 73
 64 76 74 71 73 78 71 63 63 64 70 66 78 70 74 62 61 70 69 75 75 68 72 68
 73 78 60 64 78 71 70 65 60 68 70 65 61 63 76 61 65 67 76 60 78 73 73 65
 65 73 79 61 79 67 67 64 63 63 78 70 72 76 61 66 79 61 60 68 60 76 71 64
 73 72 73 62 75 65 73 64 64 76 61 79 75 62 70 78 60 62 60 64 67 60 77 76
 61 70 67 79 77 67 61 78 62 69 73 72 68 67 67 62 66 72 77 64 75 75 74 68
 66 71 75 79 69 78 65 77 64 69 70 73 75 60 69 74 76 62 70 79 70 71 66 66
 72 63 61 67 60 63 63 71 75 70 77 68 73 62 67 71 66 73 77 66 77 73 64 73
 78 76 69 65 77 76 71 65 68 77 63 73 71 63 63 60 66 65 63 69 70 62 68 60
 69 60 76 66 73 66 62 73 61 65 69 72 70 78 74 61 69 60 72 65 77 68 63 69
 61 60 62 60 74 74 74 73 60 68 72 75 63 60 77 61 76 68 70 77 79 77 62 61
 63 64 64 68 72 72 63 60 71 73 72 73 68 65 71 64 61 72 65 63 71 78 76 74
 61 64 68 60 68 60 69 63 77 71 68 65 60 69 60 69 62 65 64 65 66 68 60 60
 64 64 65 78 74 72 74 69 71 64 70 66 71 76 64 72 66 65 66 78 66 79 73 61
 69 78 60 73 66 60 79 64 76 70 77 63 68 71 79 69 77 67 63 66 68 76 79 74
 73 60 68 73 79 67 72 62 71 79 70 71 70 74 62 65 64 79 62 79 60 76 62 77
 68 71 77 73 77 62 72 76 71 62 73 77 76 64 69 62 72 60 62 60 67 63 60 78
 73 65 68 77 78 68 72 60 77 76 69 66 77 75 74 63 71 72 66 69 78 71 79 61
 69 69 71 74 70 61 65 71 66 66 68 66 78 77 72 69 70 61 73 67 68 74 78 73
 62 63 70 76 70 64 68 79 61 75 76 75 78 68 63 75 73 73 65 79 62 69 75 72
 65 71 65 63 73 73 75 61 63 71 72 64 74 76 77 67 72 63 74 65 76 76 64 65
 73 68 67 74 78 70 65 78 64 62 67 71 65 61 79 70 67 64 79 70 77 74 69 71
 64 76 79 69 61 74 61 70 76 75 60 69 73 70 79 75 67 68 65 73 74 61 74 68
 69 78 66 60 65 76 60 75 65 63 78 63 78 66 68 78 66 76 77 73 62 67 77 67
 66 71 71 78 63 69 62 63 63 75 73 65 67 65 60 79 73 64 66 63 60 75 64 70
 61 67 63 79 74 69 66 63 64 68 61 75 74 68 70 71 69 70 72 72 62 62 64 60
 60 71 74 71 61 65 60 72 77 68 67 76 65 67 66 79 65 73 60 75 67 69 65 74
 65 71 66 64 68 72 74 77 70 60 61 69 64 60 76 78]

In [4]:
import numpy as np
import pandas as pd
total = 1000
s1 = np.random.randint(80 , 100 , total)
ss1 : pd.Series = pd.Series(s1)

s2 = np.random.randint(60 , 80 , total)
ss2 : pd.Series = pd.Series(s2)

print(len(s2))
print(len(s1))

1000
1000

In [9]:
import numpy as np
import pandas as pd
total = 1000
s1 = np.random.randint(80 , 100 , (total , 2))
ss1 : pd.DataFrame = pd.DataFrame(s1 , columns=['s1' , 's2'])

s2 = np.random.randint(60 , 80 , (total , 2))
ss2 : pd.DataFrame = pd.DataFrame(s2 , columns=['s1' , 's2'])

print(ss1)

     s1  s2
0    86  89
1    99  80
2    80  92
3    98  83
4    88  84
..   ..  ..
995  87  86
996  91  87
997  89  86
998  90  90
999  85  87

[1000 rows x 2 columns]

In [10]:
ss2

     s1  s2
0    65  62
1    76  73
2    70  66
3    62  61
4    75  74
..   ..  ..
995  66  60
996  67  77
997  71  64
998  61  61
999  71  77

[1000 rows x 2 columns]

### concatenate

In [2]:
import pandas as pd
df = pd.concat([ss1 , ss2]).reset_index(drop = True)
display(df.info())       # gives you the whole information about your object
print("==============================")
display(df.describe())
print("==============================")
display(df.head())
print("==============================")
display(df.head())
print("==============================")
display(df.tail())

NameError: name 'ss1' is not defined

In [8]:
import pandas as pd
import numpy as np
total = 1000
s1 = np.random.randint(80 , 100 , (total , 2))
ss1 : pd.DataFrame = pd.DataFrame(s1 , columns=['s1' , 's2'])

s2 = np.random.randint(60 , 80 , (total , 2))
ss2 : pd.DataFrame = pd.DataFrame(s2 , columns=['s1' , 's2'])

df = pd.concat([ss1 , ss2]).reset_index(drop = True)
df.to_csv("students.csv" , index=False)

df = pd.read_csv("students.csv")

print(df.head())

   s1  s2
0  81  82
1  89  91
2  87  91
3  84  84
4  80  90

## Apply operations on columns
* Extract one column from the DataFrame
     * dataframe["column"]
        * add new column
        * get  column with space between column text
     * dataframe.column
        * not add new column
        * not get  column with space between column text
* Extract multiple columns from DataFrame 
     * dataframe[["column1", "column2"]]
         * pass list into the df

In [10]:
df['s1']

0       81
1       89
2       87
3       84
4       80
        ..
1995    60
1996    70
1997    71
1998    75
1999    62
Name: s1, Length: 2000, dtype: int64

In [11]:
df.s1

0       81
1       89
2       87
3       84
4       80
        ..
1995    60
1996    70
1997    71
1998    75
1999    62
Name: s1, Length: 2000, dtype: int64

In [13]:
df[['s1' , 's2']]

      s1  s2
0     81  82
1     89  91
2     87  91
3     84  84
4     80  90
...   ..  ..
1995  60  70
1996  70  68
1997  71  74
1998  75  69
1999  62  67

[2000 rows x 2 columns]

### Add new column

In [28]:
df['total'] = 400   # add new column
df['total'] = 300  # update column
del df['total']   # delete column
df

      s1  s2  obtained
0     81  82       163
1     89  91       180
2     87  91       178
3     84  84       168
4     80  90       170
...   ..  ..       ...
1995  60  70       130
1996  70  68       138
1997  71  74       145
1998  75  69       144
1999  62  67       129

[2000 rows x 3 columns]

#### Now we can do all above same  things with dot method

In [20]:
df.total = 200   # this means that this method is not used for add ,update columns
df['total'] = 200
df.total = 100  # not update
del df.total  # not delete
df

      s1  s2  total
0     81  82    200
1     89  91    200
2     87  91    200
3     84  84    200
4     80  90    200
...   ..  ..    ...
1995  60  70    200
1996  70  68    200
1997  71  74    200
1998  75  69    200
1999  62  67    200

[2000 rows x 3 columns]

## Adding colmns

In [22]:
df['s1'] + df['s2']

0       163
1       180
2       178
3       168
4       170
       ...
1995    130
1996    138
1997    145
1998    144
1999    129
Length: 2000, dtype: int64

In [30]:
df['total'] = 500

In [31]:
df['obtained'] = df['s1'] + df['s2']

df

      s1  s2  obtained  total
0     81  82       163    500
1     89  91       180    500
2     87  91       178    500
3     84  84       168    500
4     80  90       170    500
...   ..  ..       ...    ...
1995  60  70       130    500
1996  70  68       138    500
1997  71  74       145    500
1998  75  69       144    500
1999  62  67       129    500

[2000 rows x 4 columns]

In [34]:
df['percentage'] = df['obtained'] / df['total'] * 100
df

      s1  s2  obtained  total  percentage
0     81  82       163    500        32.6
1     89  91       180    500        36.0
2     87  91       178    500        35.6
3     84  84       168    500        33.6
4     80  90       170    500        34.0
...   ..  ..       ...    ...         ...
1995  60  70       130    500        26.0
1996  70  68       138    500        27.6
1997  71  74       145    500        29.0
1998  75  69       144    500        28.8
1999  62  67       129    500        25.8

[2000 rows x 5 columns]

## Apply custom function on each column

In [36]:
def grade(per):
    if per >= 90:
        return 'A'
    elif per >= 80:
        return 'B'
    elif per >= 70:
        return 'C'
    elif per >= 60:
        return 'D'
    else:
        return 'F'
grade(60)

'D'

## how to apply the function on the columns

In [45]:
df['percentage'].head().apply(grade)

0    F
1    F
2    F
3    F
4    F
Name: percentage, dtype: object

## apply custom function on the multiple columnns
* loc
 * iloc
 * iat
 * at

In [48]:
df[0:10]
df.iloc[1:11]

    s1  s2  obtained  total  percentage
1   89  91       180    500        36.0
2   87  91       178    500        35.6
3   84  84       168    500        33.6
4   80  90       170    500        34.0
5   95  97       192    500        38.4
6   85  89       174    500        34.8
7   82  81       163    500        32.6
8   88  83       171    500        34.2
9   81  95       176    500        35.2
10  95  95       190    500        38.0

In [51]:
df.iloc[1:11 , 0:2]

    s1  s2
1   89  91
2   87  91
3   84  84
4   80  90
5   95  97
6   85  89
7   82  81
8   88  83
9   81  95
10  95  95

In [52]:
df.loc[1:11 , 's1':'s2']  # this is the only one type of indexing in which end is included

    s1  s2
1   89  91
2   87  91
3   84  84
4   80  90
5   95  97
6   85  89
7   82  81
8   88  83
9   81  95
10  95  95
11  95  83

In [55]:
df.at[4 , 's2']

90

In [56]:
df.iat[4 , 0]

80