# Pandas

* components of pandas 
     * series type 
     * dataframe

## difference between pandas and pandera
* Pandas is a powerful data manipulation library, widely used for data analysis and manipulation tasks. It provides data structures such as DataFrames and Series for handling and analyzing tabular data.
* Pandera is a data validation library built on top of pandas. It helps in ensuring the structure, types, and content of the data meet certain expectations, especially when dealing with pandas DataFrames and Series.

In [1]:
!pip install pandera

Collecting pandera
  Downloading pandera-0.20.4-py3-none-any.whl.metadata (15 kB)
Collecting multimethod<=1.10.0 (from pandera)
  Downloading multimethod-1.10-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: numpy>=1.19.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandera) (24.1)
Requirement already satisfied: pandas>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (2.2.2)
Requirement already satisfied: pydantic in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (2.5.3)
Collecting typeguard (from pandera)
  Downloading typeguard-4.3.0-py3-none-any.whl.metadata (3.7 kB)
Collecting typing-inspect>=0.6.0 (from pandera)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas>=1.2.0->pandera) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=1.2.0->pandera) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=1.2.0->pandera) (2023.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from typing-inspect>=0.6.0->pandera) (1.0.0)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\lenovo\anaconda3\lib\site-packages (from typing-inspect>=0.6.0->pandera) (4.11.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic->pandera) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic->pandera) (2.14.6)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pandera) (1.16.0)
Downloading pandera-0.20.4-py3-none-any.whl (259 kB)
   ---------------------------------------- 0.0/259.6 kB ? eta -:--:--
   - -------------------------------------- 10.2/259.6 kB ? eta -:--:--
   ------ -------------------------------- 41.0/259.6 kB 487.6 kB/s eta 0:00:01
   ---------- ---------------------------- 71.7/259.6 kB 563.7 kB/s eta 0:00:01
   ------------- ------------------------- 92.2/259.6 kB 581.0 kB/s eta 0:00:01
   -------------------- ----------------- 143.4/259.6 kB 607.9 kB/s eta 0:00:01
   -------------------- ----------------- 143.4/259.6 kB 607.9 kB/s eta 0:00:01
   ---------------------- --------------- 153.6/259.6 kB 458.0 kB/s eta 0:00:01
   ---------------------------- --------- 194.6/259.6 kB 535.8 kB/s eta 0:00:01
   ----------------------------- -------- 204.8/259.6 kB 518.8 kB/s eta 0:00:01
   -------------------------------- ----- 225.3/259.6 kB 491.0 kB/s eta 0:00:01
   -------------------------------------- 259.6/259.6 kB 498.7 kB/s eta 0:00:00
Downloading multimethod-1.10-py3-none-any.whl (9.9 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading typeguard-4.3.0-py3-none-any.whl (35 kB)
Installing collected packages: typing-inspect, typeguard, multimethod, pandera
Successfully installed multimethod-1.10 pandera-0.20.4 typeguard-4.3.0 typing-inspect-0.9.0

In [ ]:
import pandas as pd
import pandera as pa

In [4]:
import pandas as pd
# list is accepted
s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
import pandas as pd
# set is not acceptable
s1 = pd.Series({1, 2, 3, 4, 5})
print(s1)

TypeError: 'set' type is unordered

In [6]:
import pandas as pd
# tuple is accepted
s1 = pd.Series((1, 2, 3, 4, 5))
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
import pandas as pd

s1 = pd.Series({
                "a" : 1,
                "b" : 2
                })
print(s1)

a    1
b    2
dtype: int64

<hr>

# difference between series and list
* one difference is index is not shown on the list but shown on the pandas

In [9]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
li : list = [1,2,3,4,5]
li

[1, 2, 3, 4, 5]

<hr>

In [5]:
import pandas as pd
value = [1,2,3,4,5]
index =  ["a" , "b" , "c" , "d" , "e"]

df = pd.Series(value, index=index)

print(df)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
# multiple indexing
import pandas as pd
value = [1,2,3,4,5]
index : list[list[str]]=  [["a1" , "a1" , "a1" , "b1" , "b1"],
                           ["a" , "b" , "c" , "d" , "e"]]

df = pd.Series(value, index=index)

print(df)

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
dtype: int64

In [9]:
# multiple indexing
import pandas as pd
value = [1,2,3,4,5]
index : list[list[str]]=  [["a1" , "a1" , "a1" , "b1" , "b1"],
                           ["a" , "b" , "c" , "d" , "e"]]

df = pd.Series(value, index=index , name=  "Student Database" , dtype= "int32")

print(df)

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
Name: Student Database, dtype: int32

## Dataframe

In [3]:
import pandas as pd
s1 = pd.Series([1,2,3,4])

s2 = pd.Series([90,80,70,60] , name="marks")
s3 = pd.Series(["fatima" , "tehreem" , "ali" , "maha"] , name="student name")

df = pd.DataFrame({"student id" : s1  , "marks" : s2 , "student name" :s3 })

print(df)

   student id  marks student name
0           1     90       fatima
1           2     80      tehreem
2           3     70          ali
3           4     60         maha

In [31]:
import pandas as pd
s1 = pd.Series([1,2,3,4] , name="student id")

s2 = pd.Series([90,80,70,60] , name="marks")
s3 = pd.Series(["fatima" , "tehreem" , "ali" , "maha"] , name="student name")


df = pd.concat([s1 , s2 , s3] , axis=1)

print(df)

   student id  marks student name
0           1     90       fatima
1           2     80      tehreem
2           3     70          ali
3           4     60         maha

In [25]:
data = [1,2,3,4]
print(pd.Series(data , ["a" , "b" , "c" , "d"]))
pd.DataFrame(data , ["a" , "b" , "c" , "d"])

a    1
b    2
c    3
d    4
dtype: int64

   0
a  1
b  2
c  3
d  4

In [10]:
import pandas as pd
data = [[1,2,3,4] , 
        [4,5,6,8],
        [6,7,8,9]]

print(pd.DataFrame(data))

   0  1  2  3
0  1  2  3  4
1  4  5  6  8
2  6  7  8  9

In [13]:
import pandas as pd
data = [[1,2,3,4] , 
        [4,5,6,8],
        [6,7,8,9]]

df = pd.DataFrame(data , columns=["a" , "b" , "c" , "d"] , index=["a" , 'b' , 'c'])

df

   a  b  c  d
a  1  2  3  4
b  4  5  6  8
c  6  7  8  9

In [14]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [15]:
df.values

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [6, 7, 8, 9]], dtype=int64)

In [16]:
df.index

Index(['a', 'b', 'c'], dtype='object')

## advance level

In [31]:
import numpy as np
import pandas as pd

a = np.arange(10*10).reshape(10,10)
df = pd.DataFrame(a , columns=list("abcdefghij"))
df

    a   b   c   d   e   f   g   h   i   j
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [40]:
!pip install pandas lxml

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: lxml in c:\users\lenovo\anaconda3\lib\site-packages (5.2.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [42]:
import pandas as pd

df : list[pd.DataFrame] = pd.read_html("https://www.w3schools.com/python/python_operators.asp")


df

ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

In [41]:
import pandas as pd
df = pd.read_json("https://www.w3schools.com/python/pandas/data.js")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [48]:
!pip install pandera

^C

Requirement already satisfied: pandera in c:\users\lenovo\anaconda3\lib\site-packages (0.20.4)
Requirement already satisfied: multimethod<=1.10.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (1.10)
Requirement already satisfied: numpy>=1.19.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandera) (24.1)
Requirement already satisfied: pandas>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (2.2.2)
Requirement already satisfied: pydantic in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (2.5.3)
Requirement already satisfied: typeguard in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (4.3.0)
Requirement already satisfied: typing-inspect>=0.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (0.9.0)
Requirement already satisfied: wrapt in c:\users\lenovo\anaconda3\lib\site-packages (from pandera) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas>=1.2.0->pandera) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=1.2.0->pandera) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=1.2.0->pandera) (2023.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from typing-inspect>=0.6.0->pandera) (1.0.0)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\lenovo\anaconda3\lib\site-packages (from typing-inspect>=0.6.0->pandera) (4.11.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic->pandera) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic->pandera) (2.14.6)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pandera) (1.16.0)

In [1]:
import pandas as pd
import pandera as pa

# data to validate
df = pd.DataFrame({
    "column1": [1, 4, 0, 10, 9],
    "column2": [-1.3, -1.4, -2.9, -10.1, -20.4],
    "column3": ["value_1", "value_2", "value_3", "value_2", "value_1"],
})

# define schema
schema = pa.DataFrameSchema({
    "column1": pa.Column(int, checks=pa.Check.le(10)),
    "column2": pa.Column(float, checks=pa.Check.lt(-1.2)),
    "column3": pa.Column(str, checks=[
        pa.Check.str_startswith("value_"),
        # define custom checks as functions that take a series as input and
        # outputs a boolean or boolean Series
        pa.Check(lambda s: s.str.split("_", expand=True).shape[1] == 2)
    ]),
})

validated_df = schema(df)
print(validated_df)

ModuleNotFoundError: No module named 'pandera'

## slicing and indexing
* series_variable[index]
* DataFrame[index]
    * loc
    * iloc
    * at
    * iat

In [52]:
df = pd.Series([1,2,3,4])
print(df)
print("apply sliding")

print(df[1])

0    1
1    2
2    3
3    4
dtype: int64
apply sliding
2

In [53]:
df = pd.Series([1,2,3,4])
print(df)
print("apply sliding")

print(df[1:3])

0    1
1    2
2    3
3    4
dtype: int64
apply sliding
1    2
2    3
dtype: int64

In [56]:
df = pd.Series([1,2,3,4] , index=['a' , 'b' , 'c' , 'd'])
print(df)
print("apply sliding")

print(df.iloc[1:4]) # index location same as numpy

a    1
b    2
c    3
d    4
dtype: int64
apply sliding
b    2
c    3
d    4
dtype: int64

In [61]:
df = pd.Series([1,2,3,4] , index=['a' , 'b' , 'c' , 'd'])
print(df)
print("apply sliding")

print(df.loc['a':'d']) # index location as labels and end is must included

a    1
b    2
c    3
d    4
dtype: int64
apply sliding
a    1
b    2
c    3
d    4
dtype: int64

In [62]:
df = pd.Series([1,2,3,4] , index=['a' , 'b' , 'c' , 'd'])
print(df)
print("apply sliding")

print(df.iat[1]) # we give the index in number they give the value

a    1
b    2
c    3
d    4
dtype: int64
apply sliding
2

In [65]:
df = pd.Series([1,2,3,4] , index=['a' , 'b' , 'c' , 'd'])
print(df)
print("apply sliding")

print(df.at["b"]) # we give the index in value they give the number

a    1
b    2
c    3
d    4
dtype: int64
apply sliding
2

In [66]:
data = """
"Technology has revolutionized the way we live, work, and communicate. In the past few decades,
 the rise of the internet, smartphones, and social media platforms has transformed every aspect
   of our daily lives. Whether it’s accessing information, shopping, or staying connected 
   with friends and family across the globe, technology has made it all easier and faster. 
   Innovations in artificial intelligence and automation continue to push the boundaries of what’s 
   possible, creating opportunities in fields like medicine, education, and entertainment. However, 
   these advancements also raise important questions about privacy, security, and the impact on jobs. As technology continues to evolve, it is essential that we balance the benefits with thoughtful 
consideration of the challenges, ensuring that progress leads to a better future for all."

"""
import re
pattern = """ Whether it’s accessing information, shopping, or staying connected 
   with friends and family across the globe, technology has made it all easier and faster. """

matches = re.findall(pattern, data)
matches

[' Whether it’s accessing information, shopping, or staying connected \n   with friends and family across the globe, technology has made it all easier and faster. ']